import { ConfigService } from "@nestjs/config";

export const jwtConstants = () => {
  const s = new ConfigService();
  return {
    secret: s.get("JWT_SECRET"),
  };
};

export enum AuthErrors {
  USERNAME_TAKEN = "USERNAME_TAKEN",
  INVALID_TOKEN = "INVALID_TOKEN",
  SAME_PASSWORD = "SAME_PASSWORD",
  INVALID_HEADERS = "INVALID_HEADERS",
  UNVERIFIED_ACCOUNT = "UNVERIFIED_ACCOUNT",
  ACCOUNT_ALREADY_VERIFIED = "ACCOUNT_ALREADY_VERIFIED",
  UNKNOWN_USER = "UNKNOWN_USER",
  UNKNOWN_MEMBER = "UNKNOWN_MEMBER",
  ALREADY_REGISTERED = "ALREADY_REGISTERED",
  PASS_DOESNT_MATCH = "PASS_DOESNT_MATCH",
  SERVER_ERROR = "SERVER_ERROR",
  INSUFFICIENT_ROLE = "INSUFFICIENT_ROLE",
  INSUFFICIENT_PERMISSION = "INSUFFICIENT_PERMISSION",
  INVALID_ROLES_OR_PERMISSIONS = "INVALID_ROLES_OR_PERMISSIONS",
  ACCOUNT_SUSPENDED = "ACCOUNT_SUSPENDED",
  TOKEN_EXPIRED = "TOKEN_EXPIRED",
  INVALID_TWO_FACTOR_CODE = "INVALID_TWO_FACTOR_CODE",
  IP_BLOCKED = "IP_BLOCKED",
  SECURITY_QUESTION_FAILED = "SECURITY_QUESTION_FAILED",
  UNEXPECTED_ERROR = "UNEXPECTED_ERROR",
  PASSWORD_REUSE_NOT_ALLOWED = "PASSWORD_REUSE_NOT_ALLOWED",
  PASSWORD_RESET_EXPIRED = "PASSWORD_RESET_EXPIRED",
  UNAUTHORIZED_DEVICE = "UNAUTHORIZED_DEVICE",
  INVALID_SECURITY_KEY = "INVALID_SECURITY_KEY",
  INVALID_ORIGIN = "INVALID_ORIGIN",
  LIMIT_EXCEEDED = "LIMIT_EXCEEDED",
  SESSION_EXIRED = "SESSION_EXPIRED",
  UNAUTHORIZED_REQUEST = "UNAUTHORIZED_REQUEST",
  INVALID_INPUT = "INVALID_INPUT",
}
