import { ConfigService } from "@nestjs/config";

export const jwtConstants = () => {
  const s = new ConfigService();
  return {
    secret: s.get("JWT_SECRET"),
  };
};

export enum AuthErrors {
  INVALID_TOKEN = "INVALID_TOKEN",
  INVALID_HEADERS = "INVALID_HEADERS",
  UNVERIFIED_ACCOUNT = "UNVERIFIED_ACCOUNT",
  UNKNOWN_USER = "UNKNOWN_USER",
  ALREADY_REGISTERED = "ALREADY_REGISTERED ",
  PASS_DOESNT_MATCH = "PASS_DOESNT_MATCH",
  SERVER_ERROR = "SERVER_ERROR",
  INSUFFICIENT_ROLE = "INSUFFICIENT_ROLE",
  INSUFFICIENT_PERMISSION = "INSUFFICIENT_PERMISSION",
  INVALID_ROLES_OR_PERMISSIONS = "INVALID_ROLES_OR_PERMISSIONS",
  ACCOUNT_SUSPENDED = "ACCOUNT_SUSPENDED",
}
